<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\..\common.props" />

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <RootNamespace>Masroof.Ecommerce</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Masroof.Ecommerce.Domain\Masroof.Ecommerce.Domain.csproj" />
    <ProjectReference Include="..\Masroof.Ecommerce.Application.Contracts\Masroof.Ecommerce.Application.Contracts.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Volo.Abp.PermissionManagement.Application" Version="9.3.6" />
    <PackageReference Include="Volo.Abp.FeatureManagement.Application" Version="9.3.6" />
    <PackageReference Include="Volo.Abp.SettingManagement.Application" Version="9.3.6" />
    <PackageReference Include="Volo.Abp.Account.Pro.Public.Application" Version="9.3.6" />
    <PackageReference Include="Volo.Abp.Account.Pro.Admin.Application" Version="9.3.6" />
    <PackageReference Include="Volo.Abp.Identity.Pro.Application" Version="9.3.6" />
    <PackageReference Include="Volo.Abp.AuditLogging.Application" Version="9.3.6" />
    <PackageReference Include="Volo.Abp.OpenIddict.Pro.Application" Version="9.3.6" />
    <PackageReference Include="QuestPDF" Version="2024.10.3" />
    <PackageReference Include="Stripe.net" Version="47.4.0" />
  </ItemGroup>

</Project>
